name: Branch build
run-name: Branch build by ${{ github.actor }} ğŸš€
on: [push]

jobs:
  build:
    name: 'ğŸ› ï¸ Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/goldstack-setup

  lint:
    name: 'ğŸ–‹ï¸ Prettier and Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/goldstack-setup
      - run: |
          yarn format-check
          yarn lint

  get-packages:
    name: 'ğŸ“¦ Get Packages'
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set-packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v3
      - id: set-packages
        run: |
          PACKAGES=$(ls -d packages/*/ | cut -f2 -d'/' | jq -R -s -c 'split("\n")[:-1]')
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT

  test:
    name: 'ğŸ” Tests (${{ matrix.package }})'
    needs: get-packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.get-packages.outputs.packages) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4 # used for local DynamoDB
        with:
          distribution: 'temurin'
          java-version: '20'
      - uses: ./.github/actions/goldstack-setup
      - run: |
          cd packages/${{ matrix.package }}
          yarn test

  audit:
    name: 'ğŸ”’ NPM Audit'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/goldstack-setup
      - run: |
          yarn npm audit --all --recursive --severity critical
